/* ══════════════ PLAIN-LANGUAGE LAYER ══════════════
   WHO  — the person each view follows, shown as a card under the title.
   PLAIN — one plain-language paragraph per step, keyed by view id and step
   index. Kept out of the view files so those stay readable, and so the plain
   layer can be written and reviewed as one continuous piece of prose. */

const WHO = {
  trader: { k:'B', n:'Bob',   r:[['Taker','Taker'],],
    l:['Bob has 50,000 USDC and wants EV. He is not patient, he is not clever, and he is not going to read any of this. He just presses swap.',
       "Bob a 50 000 USDC et veut de l'EV. Il n'est pas patient, il n'est pas malin, et il ne lira rien de tout ceci. Il appuie sur swap."] },
  maker: { k:'A', n:'Alice',
    l:['Alice thinks EV is 5 % too expensive today. She is willing to wait weeks for her price, and she wants to be able to change her mind at any moment.',
       "Alice trouve l'EV 5 % trop cher aujourd'hui. Elle accepte d'attendre des semaines son prix, et elle veut pouvoir changer d'avis à tout instant."] },
  lent: { k:'N', n:'Nadia',
    l:['Nadia wants exactly what Alice wants, with one extra demand: while her money waits for that price, it should be earning something.',
       "Nadia veut exactement la même chose qu'Alice, avec une exigence en plus : pendant que son argent attend ce prix, il doit rapporter quelque chose."] },
  borrow: { k:'D', n:'David',
    l:['David holds 10,000 EV and needs 6,000 USDC in cash. Selling is out of the question, so he borrows against what he owns.',
       "David détient 10 000 EV et a besoin de 6 000 USDC en liquide. Vendre est hors de question, donc il emprunte contre ce qu'il possède."] },
  lev: { k:'E', n:'Elena',
    l:['Elena has 5,000 USDC and a conviction: EV is going up. She wants a position several times bigger than her money allows.',
       "Elena a 5 000 USDC et une conviction : EV va monter. Elle veut une position plusieurs fois plus grosse que ce que son argent permet."] },
  lp: { k:'F', n:'Farid',
    l:['Farid supplies the money the other five are using. He earns from all of their activity, and he is the one who pays if a loan goes bad.',
       "Farid fournit l'argent que les cinq autres utilisent. Il gagne sur toute leur activité, et c'est lui qui paie si un prêt tourne mal."] }
};

const PLAIN = {

overview: [
 ['Somebody has to put the money in first. Farid deposits both tokens. From that moment his money is doing three jobs at once, whether he thinks about it or not — and it is also the money that will absorb a loss if one happens.',
  "Il faut bien que quelqu'un mette l'argent en premier. Farid dépose les deux tokens. Dès cet instant son argent fait trois métiers à la fois, qu'il y pense ou non, et c'est aussi l'argent qui absorbera une perte s'il y en a une."],
 ['Job one: quoting a price. When Bob wants to swap, the pool works out the price from how much of each token it is holding. More of one, less of the other, and the price moves. Nobody sets it by hand.',
  "Métier un : coter un prix. Quand Bob veut échanger, la réserve calcule le prix à partir de la quantité qu'elle détient de chaque token. Plus de l'un, moins de l'autre, et le prix bouge. Personne ne le fixe à la main."],
 ['Job two: lending. The exact same tokens are what David borrows. Nothing is moved or copied — borrowing does not change the price at all, the pool just notes down who owes what.',
  "Métier deux : prêter. Ces mêmes tokens sont ce que David emprunte. Rien n'est déplacé ni copié : emprunter ne change pas le prix, la réserve note simplement qui doit quoi."],
 ['Job three: holding standing orders. Alice cannot pick just any price — she picks a rung on a fixed ladder, where each rung is 1 % from the next. That sounds like a limitation, but it is what lets the pool settle a thousand orders at once instead of one at a time.',
  "Métier trois : garder les ordres en attente. Alice ne peut pas choisir n'importe quel prix : elle choisit un barreau sur une échelle fixe, chaque barreau à 1 % du suivant. Cela ressemble à une contrainte, mais c'est ce qui permet à la réserve de régler mille ordres d'un coup au lieu d'un par un."],
 ['And here is the loop nobody had closed before. Nadia\'s money is sitting there waiting for a price. Why should it sleep? She ticks a box, and it gets lent to David while it waits. When her price finally arrives, the amount that trades is bigger than what she put in.',
  "Et voici la boucle que personne n'avait fermée avant. L'argent de Nadia est là, à attendre un prix. Pourquoi dormirait-il ? Elle coche une case, et il est prêté à David pendant l'attente. Quand son prix finit par arriver, le montant qui s'échange est plus gros que ce qu'elle avait mis."],
 ['One contract holds all of it. It never asks anything outside itself for a price, and nobody has to be paid to keep it running. Its only inputs are what people deposit, what people trade, and the passage of time.',
  "Un seul contrat détient l'ensemble. Il ne demande jamais un prix à l'extérieur, et personne n'a besoin d'être payé pour le faire tourner. Ses seules entrées sont ce que les gens déposent, ce qu'ils échangent, et le temps qui passe."]
],

trader: [
 ['Before Bob arrives, three people have already left standing orders on the price ladder, each saying "sell me EV if the price gets here". One of them is stale: the price already went past it during an earlier swing, so that order is sitting there offering a bargain nobody has taken yet.',
  "Avant que Bob n'arrive, trois personnes ont déjà laissé des ordres en attente sur l'échelle de prix, chacun disant « vends-moi de l'EV si le prix arrive ici ». L'un d'eux est périmé : le prix l'a déjà dépassé lors d'un mouvement antérieur, donc cet ordre est posé là à offrir une affaire que personne n'a encore prise."],
 ['Bob presses swap with 50,000 USDC. He has no idea any of those orders exist, and he does not need to. He will not choose anything from here on.',
  "Bob appuie sur swap avec 50 000 USDC. Il ignore totalement que ces ordres existent, et il n'a pas besoin de le savoir. Il ne choisira plus rien à partir d'ici."],
 ['The fee is taken first, off the whole amount, before anything else happens. This matters more than it sounds: because the fee is fixed before the pool decides where Bob\'s money goes, the pool has no way to earn more by ignoring somebody\'s order. It cannot cheat the people waiting.',
  "La fee est prélevée en premier, sur la totalité, avant que quoi que ce soit d'autre n'arrive. C'est plus important qu'il n'y paraît : comme la fee est fixée avant que la réserve ne décide où va l'argent de Bob, la réserve n'a aucun moyen de gagner plus en ignorant l'ordre de quelqu'un. Elle ne peut pas léser ceux qui attendent."],
 ['The stale order gets served first, because it is the best price on the table. Bob gets 5,050 EV for 5,000 USDC — better than the pool would have given him — and the price does not budge, because this trade happened between him and that order directly.',
  "L'ordre périmé est servi en premier, parce que c'est le meilleur prix sur la table. Bob obtient 5 050 EV pour 5 000 USDC, mieux que ce que la réserve lui aurait donné, et le prix ne bouge pas d'un pouce, parce que cet échange s'est fait directement entre lui et cet ordre."],
 ['Now Bob\'s remaining money starts pushing the price up, and it walks into the next order on the ladder. That person gets exactly the price they asked for. Not approximately: exactly. They wrote 1.000, they get 1.000.',
  "Maintenant l'argent restant de Bob commence à pousser le prix vers le haut, et il tombe sur l'ordre suivant de l'échelle. Cette personne obtient exactement le prix qu'elle avait demandé. Pas approximativement : exactement. Elle avait écrit 1.000, elle obtient 1.000."],
 ['Same again one rung up. And notice what these people did not pay: no fee, and no slippage. Bob already covered the fee at the start, and their price was fixed in advance. Waiting turns out to be well paid here.',
  "Rebelote un barreau plus haut. Et remarquez ce que ces gens n'ont pas payé : ni fee, ni slippage. Bob a déjà couvert la fee au départ, et leur prix était fixé d'avance. Attendre se révèle bien payé ici."],
 ['Whatever is left after all the waiting orders are used up finally goes to the pool itself, in one go. This last chunk is the only part of Bob\'s trade that actually moves the pool\'s tokens around.',
  "Ce qui reste une fois tous les ordres en attente épuisés va enfin à la réserve elle-même, d'un seul coup. Ce dernier morceau est la seule partie de l'échange de Bob qui déplace réellement les tokens de la réserve."],
 ['Add it up: Bob got about 1.3 % more EV than he would have from the pool alone, purely because other people were patiently waiting at good prices. He did nothing clever. The rule is simple — the more orders are waiting, the better the price everyone gets.',
  "Faisons le total : Bob a obtenu environ 1,3 % d'EV en plus que ce que la réserve seule lui aurait donné, uniquement parce que d'autres gens attendaient patiemment à de bons prix. Il n'a rien fait d'astucieux. La règle est simple : plus il y a d'ordres en attente, meilleur est le prix pour tout le monde."],
 ['One catch, and it only bites a certain kind of trader. If Bob had jumped in seconds after a big crash, hoping to scoop the dip, the pool would have charged him a premium for it. Wait a few minutes and that premium is gone. The system is built to reward patience and to make sniping unprofitable.',
  "Un piège, et il ne mord qu'un certain type de trader. Si Bob avait sauté quelques secondes après un gros krach, en espérant ramasser la baisse, la réserve lui aurait facturé une prime pour ça. Attendez quelques minutes et cette prime disparaît. Le système est fait pour récompenser la patience et rendre le sniping non rentable."]
],

maker: [
 ['Alice puts 10,000 USDC on the rung marked 0.950, roughly 5 % below today\'s price. The contract holds that money for her. It is not mixed into the pool, it is not lent to anyone, it is just parked with her name on it.',
  "Alice pose 10 000 USDC sur le barreau marqué 0.950, environ 5 % sous le prix du jour. Le contrat garde cet argent pour elle. Il n'est pas mélangé à la réserve, il n'est prêté à personne, il est simplement garé à son nom."],
 ['And this is her real advantage: she can take it back whenever she likes. Instantly, no conditions, no queue, whatever state the pool is in. Because her money was never lent to anybody, nobody has to give it back first.',
  "Et c'est là son vrai avantage : elle peut le reprendre quand elle veut. Instantanément, sans condition, sans file d'attente, quel que soit l'état de la réserve. Comme son argent n'a jamais été prêté à personne, personne n'a besoin de le rendre d'abord."],
 ['Weeks pass. The price wanders around, then breaks downward toward her rung. Alice does nothing at all — and importantly, nobody has to be found to take the other side of her trade. She is not waiting for a buyer, she is waiting for a price.',
  "Des semaines passent. Le prix vagabonde, puis casse vers le bas en direction de son barreau. Alice ne fait absolument rien, et surtout, personne n'a besoin d'être trouvé pour prendre l'autre côté de son échange. Elle n'attend pas un acheteur, elle attend un prix."],
 ['Someone sells through her level, and she is filled at exactly 0.950. She gets 10,526 EV. The pool does not go through her order one by one — it settles the whole rung in a single operation, so a rung holding ten thousand orders costs the same as a rung holding one.',
  "Quelqu'un vend à travers son niveau, et elle est remplie à exactement 0.950. Elle reçoit 10 526 EV. La réserve ne parcourt pas les ordres un par un : elle règle le barreau entier en une seule opération, donc un barreau qui porte dix mille ordres coûte autant qu'un barreau qui en porte un."],
 ['She also gets a small kickback from the trading fee Bob paid, as a thank-you for having provided the depth. And her EV is set aside for her the instant the trade happens. Whatever else goes wrong in this pool afterwards, that money is untouchable and she can always collect it.',
  "Elle touche aussi une petite ristourne sur la fee qu'a payée Bob, en remerciement de la profondeur fournie. Et son EV est mis de côté pour elle à l'instant même de l'échange. Quoi qu'il arrive de travers dans cette réserve ensuite, cet argent est intouchable et elle pourra toujours le récupérer."],
 ['Now the uncomfortable part. The price does not stop at 0.950 — it keeps falling to 0.90. Alice bought at 5 % above where the market ended up. This is the market maker\'s permanent problem: you get filled precisely when the market is walking away from you. Her little kickback does not come close to covering it.',
  "Maintenant la partie désagréable. Le prix ne s'arrête pas à 0.950, il continue jusqu'à 0.90. Alice a acheté 5 % au-dessus de là où le marché a fini. C'est le problème permanent du market maker : on est rempli précisément quand le marché s'éloigne. Sa petite ristourne est loin de compenser ça."],
 ['But look at what actually happened to her: she lost money on the market, not to the protocol. She could have cancelled for free right up to the last second, and what she received is hers no matter what. That distinction matters — of everyone in this guide, Alice is the only one nothing can hold up.',
  "Mais regardez ce qui lui est vraiment arrivé : elle a perdu de l'argent sur le marché, pas à cause du protocole. Elle pouvait annuler gratuitement jusqu'à la dernière seconde, et ce qu'elle a reçu lui appartient quoi qu'il arrive. Cette distinction compte : de tous les gens de ce guide, Alice est la seule que rien ne peut bloquer."]
],

lent: [
 ['Nadia places the identical order as Alice — 10,000 USDC waiting at 0.950 — and ticks one extra box: lend it while it waits. That box can never be un-ticked for this order.',
  "Nadia pose exactement le même ordre qu'Alice, 10 000 USDC en attente à 0.950, et coche une case en plus : prête-le pendant l'attente. Cette case ne pourra jamais être décochée pour cet ordre."],
 ['There are limits on how much waiting money can be lent, so her order has to fit. If it does not fit in full, the whole thing is refused outright. It will never quietly lend half and leave the rest — you get what you asked for or nothing, so you always know which one you have.',
  "Il y a des limites à la quantité d'argent en attente qui peut être prêtée, donc son ordre doit rentrer. S'il ne rentre pas en entier, tout est refusé net. Jamais la moitié prêtée en douce et le reste non : vous obtenez ce que vous avez demandé, ou rien, donc vous savez toujours où vous en êtes."],
 ['Her money joins the pot that David borrows from. The share of that pot currently out on loan goes from 41 % to 63 %. Notice what just happened: the pool can now lend more, and no liquidity provider had to put in another cent.',
  "Son argent rejoint le pot dans lequel David emprunte. La part de ce pot actuellement prêtée passe de 41 à 63 %. Remarquez ce qui vient de se produire : la réserve peut prêter davantage, et aucun liquidity provider n'a eu à mettre un centime de plus."],
 ['Eight months later her order is worth 10,640 USDC instead of 10,000. This is not interest sitting in a separate account — it is the order itself that grew. When her price finally arrives, 10,640 USDC will be exchanged, not 10,000.',
  "Huit mois plus tard son ordre vaut 10 640 USDC au lieu de 10 000. Ce ne sont pas des intérêts posés sur un compte à côté : c'est l'ordre lui-même qui a grossi. Quand son prix arrivera enfin, ce sont 10 640 USDC qui seront échangés, pas 10 000."],
 ['Then Nadia changes her mind and wants her money back. Meanwhile, a lot of trading has drained the pool, and more is currently lent out than there is comfortably available. The protocol allows this state on purpose — it fixes it by raising rates rather than by forbidding it.',
  "Puis Nadia change d'avis et veut récupérer son argent. Sauf qu'entre-temps, beaucoup d'échanges ont vidé la réserve, et il y a actuellement plus d'argent prêté que confortablement disponible. Le protocole autorise cet état exprès : il le corrige en montant les taux plutôt qu'en l'interdisant."],
 ['So her cancellation is refused. Not delayed in a queue, not partially paid, not swapped for an IOU — the transaction simply does not go through, and she has to try again later. This is the whole price of the extra yield, and it is worth being blunt about it: nobody can tell her when it will clear.',
  "Son annulation est donc refusée. Ni mise en file d'attente, ni payée en partie, ni échangée contre une reconnaissance de dette : la transaction ne passe simplement pas, et elle devra réessayer plus tard. C'est tout le prix du rendement supplémentaire, et autant être direct : personne ne peut lui dire quand ça passera."],
 ['What is working in her favour is money, not promises. Borrowing now costs 47 %, which pays people very well to repay their loans and to deposit fresh funds. Anyone can unblock the pool by lending into it — including Nadia herself, if she wants out badly enough.',
  "Ce qui joue en sa faveur, c'est de l'argent, pas des promesses. Emprunter coûte maintenant 47 %, ce qui paie très bien les gens pour rembourser leurs prêts et déposer des fonds frais. N'importe qui peut débloquer la réserve en y prêtant, Nadia comprise, si elle veut sortir suffisamment fort."],
 ['Repayments arrive, the pressure drops, and she withdraws all 10,640 USDC in actual tokens. She was never at risk of losing money here — she was at risk of not being able to leave when she wanted to. Those are two very different things, and it is worth knowing which one you are signing up for.',
  "Les remboursements arrivent, la pression retombe, et elle retire ses 10 640 USDC en vrais tokens. Elle n'a jamais risqué de perdre de l'argent ici : elle a risqué de ne pas pouvoir partir quand elle le voulait. Ce sont deux choses très différentes, et il vaut mieux savoir laquelle on signe."]
],

borrow: [
 ['David owns 10,000 EV and needs 6,000 USDC. He does not want to sell, because he thinks EV is going up. So he does what people have always done with something valuable: he pawns it.',
  "David possède 10 000 EV et a besoin de 6 000 USDC. Il ne veut pas vendre, parce qu'il pense que EV va monter. Il fait donc ce qu'on a toujours fait avec un objet de valeur : il le met en gage."],
 ['Here is the unusual part: David chooses the price at which he agrees to be wiped out. He picks 0.78, about 22 % below today. Because he picked a low, safe-feeling level, the pool asks him for a lot of collateral: 8,308 of his 10,000 EV. He keeps the rest.',
  "Voici la partie inhabituelle : David choisit le prix auquel il accepte d'être liquidé. Il prend 0.78, environ 22 % sous le prix du jour. Comme il a choisi un niveau bas et rassurant, la réserve lui demande beaucoup de collateral : 8 308 de ses 10 000 EV. Il garde le reste."],
 ['Four checks run before the loan opens. The important one to understand: the pool refuses to lend on terms cheaper than simply swapping. If borrowing and walking away were ever cheaper than trading, people would do exactly that, and the pool would be robbed one loan at a time.',
  "Quatre contrôles tournent avant l'ouverture du prêt. Celui qu'il faut comprendre : la réserve refuse de prêter à des conditions moins chères que simplement échanger. Si emprunter puis disparaître était moins cher qu'échanger, les gens feraient exactement ça, et la réserve serait dévalisée prêt après prêt."],
 ['EV rises 21 %. David is delighted and does nothing. No margin call, no notification, no oracle to worry about. His loan just sits there — and he can even sell the whole position to someone else, or have a third party service it, without handing over his keys.',
  "EV monte de 21 %. David est ravi et ne fait rien. Aucun appel de marge, aucune notification, aucun oracle à surveiller. Son prêt reste simplement là, et il peut même vendre la position entière à quelqu'un d'autre, ou la faire gérer par un tiers, sans céder ses clés."],
 ['Now the part almost nobody expects. His liquidation price is not fixed. Interest is piling up on his debt, and instead of billing him for it, the protocol quietly raises the level at which he gets wiped out. After eighteen months his 0.78 has become 0.92. The market did nothing. His safety margin went from 22 % to 8 % on its own.',
  "Maintenant la partie que presque personne n'anticipe. Son prix de liquidation n'est pas fixe. Les intérêts s'accumulent sur sa dette, et au lieu de les lui facturer, le protocole remonte discrètement le niveau auquel il est liquidé. Après dix-huit mois, son 0.78 est devenu 0.92. Le marché n'a rien fait. Sa marge de sécurité est passée de 22 % à 8 % toute seule."],
 ['Then EV falls back. On the day he opened, this move would have left him completely safe with room to spare. Today it does not, and nothing told him that. The number he was watching never changed — the line came up to meet him.',
  "Puis EV redescend. Le jour où il a ouvert, ce mouvement l'aurait laissé totalement en sécurité, avec de la marge. Aujourd'hui non, et rien ne l'en a averti. Le chiffre qu'il surveillait n'a jamais changé : c'est la ligne qui est montée à sa rencontre."],
 ['At 0.90 the two lines touch and his loan is underwater. The pool does not check loans one by one to find out — every loan sitting at or below the current price is underwater by definition, so it finds all of them instantly, however many there are.',
  "À 0.90 les deux lignes se touchent et son prêt est sous l'eau. La réserve ne vérifie pas les prêts un par un pour le découvrir : tout prêt situé au niveau du prix courant ou en dessous est sous l'eau par définition, donc elle les trouve tous instantanément, quel que soit leur nombre."],
 ['His collateral is taken. All of it. There is no auction, no negotiation, and nothing handed back — the pool keeps the 8,308 EV and the debt is gone. Everyone else sitting on that same rung is closed in the very same operation.',
  "Son collateral est saisi. En totalité. Pas d'enchère, pas de négociation, et rien qui lui revienne : la réserve garde les 8 308 EV et la dette disparaît. Tous ceux qui étaient sur le même barreau sont fermés dans la même opération."],
 ['The scoreboard: EV dropped 10 %, and David is 16 % worse off than if he had simply sat on his tokens and done nothing. And there was no way to automate an escape — this protocol attaches no stop-loss and no take-profit to a loan. A borrowing position here is something you have to actually watch.',
  "Le compte final : EV a baissé de 10 %, et David est 16 % plus pauvre que s'il était resté assis sur ses tokens sans rien faire. Et il n'existait aucun moyen d'automatiser une sortie : ce protocole n'attache ni stop-loss ni take-profit à un prêt. Une position d'emprunt ici, il faut la surveiller pour de vrai."]
],

lev: [
 ['Elena has 5,000 USDC and thinks EV is going up. She wants a position worth several times that. There is no leverage slider anywhere — she is going to build it out of ordinary borrowing, in one transaction.',
  "Elena a 5 000 USDC et pense que EV va monter. Elle veut une position qui vaut plusieurs fois ça. Il n'y a de curseur de levier nulle part : elle va la construire à partir d'emprunts ordinaires, en une seule transaction."],
 ['The trick that makes it possible: she can borrow the pool\'s cash for free, as long as she gives it back before her transaction ends. Since the loan cannot outlive the transaction, it needs no collateral. She uses it as scaffolding, and it is gone by the time anyone could notice.',
  "L'astuce qui rend ça possible : elle peut emprunter la trésorerie de la réserve gratuitement, à condition de la rendre avant la fin de sa transaction. Comme le prêt ne peut pas survivre à la transaction, il ne demande aucun collateral. Elle s'en sert d'échafaudage, et il a disparu avant que quiconque ait pu le remarquer."],
 ['One turn of the loop: borrow USDC, swap it into EV, put that EV up as collateral, borrow again against it. Her exposure goes from 5,000 to 8,400. Then she does it again.',
  "Un tour de boucle : emprunter des USDC, les échanger contre de l'EV, poser cet EV en collateral, réemprunter contre lui. Son exposition passe de 5 000 à 8 400. Puis elle recommence."],
 ['Each turn adds less than the one before, because each turn has costs: the pool asks for more collateral than the loan is worth, and she pays a bit of slippage swapping. So the loop runs out of steam by itself after a handful of turns. Nothing stops it — it just stops being worth doing.',
  "Chaque tour ajoute moins que le précédent, parce que chaque tour a un coût : la réserve demande plus de collateral que ne vaut le prêt, et elle paie un peu de slippage à chaque échange. La boucle s'essouffle donc d'elle-même après une poignée de tours. Rien ne l'arrête : elle cesse simplement d'être rentable."],
 ['She lands at 17,000 of exposure on 5,000 of her own money — about 3.4 times. Nobody set that limit. It fell out of the fees and the collateral rules. Which also means: your maximum leverage is written nowhere on screen, and you have to work it out.',
  "Elle atterrit à 17 000 d'exposition pour 5 000 d'argent à elle, soit environ 3,4 fois. Personne n'a fixé cette limite. Elle est tombée toute seule des fees et des règles de collateral. Ce qui veut aussi dire : votre levier maximum n'est écrit nulle part à l'écran, et il faut le calculer."],
 ['On a normal leverage venue you pay a funding rate to hold your position. Here there is no such thing — you simply pay interest on what you borrowed. When everyone piles in on the same side, borrowing gets expensive by itself, which does the same job without anyone designing it.',
  "Sur une plateforme de levier classique, on paie un funding rate pour tenir sa position. Ici ça n'existe pas : on paie simplement les intérêts de ce qu'on a emprunté. Quand tout le monde se rue du même côté, emprunter devient cher tout seul, ce qui fait le même travail sans que personne ne l'ait conçu."],
 ['If EV rises 20 %, Elena makes 68 % on her money. If it falls to her chosen level, everything she posted is taken — not the part that covers the debt, all of it. And the same silent drift that caught David is working on her too, three times faster relative to her stake. Nothing closes this position for her.',
  "Si EV monte de 20 %, Elena gagne 68 % sur son argent. S'il tombe à son niveau choisi, tout ce qu'elle a posé est saisi : pas la part qui couvre la dette, la totalité. Et la même dérive silencieuse qui a rattrapé David travaille aussi contre elle, trois fois plus vite en proportion de sa mise. Rien ne referme cette position à sa place."]
],

lp: [
 ['Farid deposits 50,000 of each token. In return he gets shares of the pool. He does not get to choose whether his money is lent out — that is not a setting, it is what the pool is. His tokens are the price on the screen and the loan book, at the same time.',
  "Farid dépose 50 000 de chaque token. En retour il reçoit des parts de la réserve. Il ne choisit pas si son argent est prêté : ce n'est pas un réglage, c'est ce qu'est la réserve. Ses tokens sont le prix affiché à l'écran et le carnet de prêts, en même temps."],
 ['Income one: every time Bob swaps, Farid earns a cut. The cut is not fixed — trades that push the pool further out of balance pay more, trades that bring it back pay less. He is being paid for the inconvenience.',
  "Revenu un : chaque fois que Bob échange, Farid touche une part. Cette part n'est pas fixe : les échanges qui déséquilibrent davantage la réserve paient plus, ceux qui la rééquilibrent paient moins. Il est payé pour le dérangement."],
 ['Income two: every time David pays interest, Farid gets a slice of that too. This is the headline of the whole protocol. Anywhere else he would have to choose — provide liquidity on an exchange, or lend on a lending platform. Here one deposit does both, and gets paid twice.',
  "Revenu deux : chaque fois que David paie des intérêts, Farid en touche une part aussi. C'est l'argument phare de tout le protocole. Partout ailleurs il devrait choisir : fournir de la liquidité sur un exchange, ou prêter sur une plateforme de prêt. Ici un seul dépôt fait les deux, et est payé deux fois."],
 ['There are quieter earnings on top. When a borrower like David gets wiped out and his collateral had been lent, the interest that collateral had earned goes to Farid rather than back to the borrower. Small, but it adds up.',
  "Il y a des revenus plus discrets par-dessus. Quand un emprunteur comme David est liquidé et que son collateral avait été prêté, les intérêts que ce collateral avait gagnés reviennent à Farid plutôt qu'à l'emprunteur. C'est petit, mais ça s'accumule."],
 ['Now the other side of the deal, and it is the single most important thing on this page. When the pool owes money to several kinds of people at once, there is a strict order of who gets paid. Farid is last on that list.',
  "Maintenant l'autre côté du marché, et c'est la chose la plus importante de cette page. Quand la réserve doit de l'argent à plusieurs sortes de gens en même temps, il y a un ordre strict de qui est payé. Farid est le dernier de cette liste."],
 ['A big borrower goes underwater in a fast crash. The pool takes their collateral, but by the time it can actually sell it, it is worth less than the debt. Somebody has to eat that gap.',
  "Un gros emprunteur passe sous l'eau dans un krach rapide. La réserve saisit son collateral, mais le temps qu'elle puisse vraiment le revendre, il vaut moins que la dette. Quelqu'un doit avaler cet écart."],
 ['Not Alice — her filled order was set aside for her the second it happened. Not the people who never lent anything — that money was never touched. Not Nadia — her balance is guaranteed never to be cut, only delayed. The loss passes all of them and arrives at Farid.',
  "Pas Alice : son ordre rempli a été mis de côté pour elle à la seconde où c'est arrivé. Pas ceux qui n'ont jamais rien prêté : cet argent n'a jamais été touché. Pas Nadia : son solde a la garantie de ne jamais être coupé, seulement retardé. La perte les traverse tous et arrive chez Farid."],
 ['His shares are simply written down. This is not a bug or an oversight — it is the design. Somebody has to be the buffer, and the whole reason the other three can be promised "at worst you wait" is that Farid is standing underneath them.',
  "Ses parts sont simplement dévaluées. Ce n'est ni un bug ni un oubli : c'est le design. Il faut bien que quelqu'un soit le tampon, et si on peut promettre aux trois autres « au pire vous attendez », c'est précisément parce que Farid se tient en dessous."],
 ['And while any of this is unresolved, he cannot leave — nor can anyone else join. That feels harsh, and it is also what stops a bank run that would guarantee everyone loses. Meanwhile the ordinary business of the pool keeps running, and it is that activity which slowly repairs it.',
  "Et tant que tout ça n'est pas réglé, il ne peut pas partir, et personne d'autre ne peut entrer. Ça paraît dur, et c'est aussi ce qui empêche la ruée qui garantirait que tout le monde perde. Pendant ce temps l'activité ordinaire de la réserve continue, et c'est elle qui la répare peu à peu."],
 ['So the yield is real, and so is what it pays for. Farid is not just a depositor earning a rate — he is the buffer that makes everyone else\'s guarantees possible. That is the trade, stated plainly, and it is worth understanding before deciding whether the rate is generous or thin.',
  "Le rendement est donc réel, et ce qu'il paie l'est tout autant. Farid n'est pas un simple déposant qui touche un taux : c'est le tampon qui rend possibles les garanties de tous les autres. Voilà le marché, dit simplement, et il vaut mieux le comprendre avant de juger si le taux est généreux ou maigre."]
],

band: [
 ['A lending protocol needs to know what things are worth. Almost all of them ask an outside service, which is exactly what attackers go after. This one asks nobody. Instead it keeps two markers of its own, one above and one below the live price, and slides them back toward it over a few minutes.',
  "Un protocole de prêt a besoin de savoir ce que valent les choses. Presque tous demandent à un service extérieur, ce qui est exactement ce que visent les attaquants. Celui-ci ne demande à personne. Il garde deux repères à lui, un au-dessus et un en dessous du prix live, et les fait glisser vers lui en quelques minutes."],
 ['An attacker borrows a huge amount, dumps it into the pool, and shoves the price up 25 % in a single instant. On a protocol that trusts an outside price feed, this is the moment they steal something.',
  "Un attaquant emprunte une somme énorme, la déverse dans la réserve, et pousse le prix de 25 % en un instant. Sur un protocole qui fait confiance à un prix extérieur, c'est le moment où il vole quelque chose."],
 ['Nothing happens. The two markers only move once per block, and they already moved for this one, using the price from before the attack. So the trading price jumped, but the price used for loans did not move a millimetre. The attack cannot pay for itself in the same instant it happens.',
  "Rien ne se passe. Les deux repères ne bougent qu'une fois par bloc, et ils ont déjà bougé pour celui-ci, en utilisant le prix d'avant l'attaque. Le prix d'échange a donc bondi, mais le prix utilisé pour les prêts n'a pas bougé d'un millimètre. L'attaque ne peut pas se payer dans l'instant même où elle a lieu."],
 ['A moment later, the upper marker does jump up to meet the new price. But the lower one does not — it only ever drifts slowly. Deliberately, the two markers do not move symmetrically.',
  "Un instant plus tard, le repère du haut saute bien jusqu'au nouveau prix. Mais celui du bas, non : il ne fait que dériver lentement. Délibérément, les deux repères ne bougent pas de façon symétrique."],
 ['So the attacker sells back to close the trade and pocket the difference, paying a second round of costs to do it. The price comes back down, and now the lower marker snaps down with it.',
  "L'attaquant revend donc pour boucler l'opération et empocher la différence, en payant une seconde série de coûts au passage. Le prix redescend, et cette fois le repère du bas claque vers le bas avec lui."],
 ['Look at where the two markers ended up: far apart. And whenever the protocol needs a price, it always picks whichever of the two is least favourable to whoever is asking. The attacker paid twice, moved the price twice, and the only thing they achieved was making the protocol more cautious with them. Whichever direction you attack from, the same thing happens.',
  "Regardez où les deux repères ont fini : très écartés. Et chaque fois que le protocole a besoin d'un prix, il prend toujours celui des deux qui est le moins favorable au demandeur. L'attaquant a payé deux fois, déplacé le prix deux fois, et la seule chose qu'il a obtenue est de rendre le protocole plus méfiant avec lui. Quelle que soit la direction d'attaque, il se passe la même chose."],
 ['There is a side effect that catches ordinary traders too. For a few minutes after any big move, buying the dip costs a premium. Not to punish anyone — it is the same mechanism, seen from the trading side. Wait for the markers to settle and it costs nothing.',
  "Il y a un effet de bord qui rattrape aussi les traders ordinaires. Pendant quelques minutes après un gros mouvement, acheter la baisse coûte une prime. Ce n'est pas pour punir qui que ce soit : c'est le même mécanisme, vu du côté échange. Attendez que les repères se referment et ça ne coûte rien."],
 ['And here is the honest cost, which the whitepaper states itself. Because the credit price is deliberately slow, real liquidations are slow too. A loan that should have been closed sits open a little longer while the markers catch up. That is the price of making manipulation worthless, and it is a price somebody pays.',
  "Et voici le coût honnête, que le whitepaper énonce lui-même. Comme le prix de crédit est délibérément lent, les vraies liquidations le sont aussi. Un prêt qui aurait dû être fermé reste ouvert un peu plus longtemps le temps que les repères rattrapent. C'est le prix à payer pour rendre la manipulation sans valeur, et c'est un prix que quelqu'un paie."]
],

liq: [
 ['Loans here are not filed by who took them or when. They are filed by the price at which they die. Every loan sitting on the same rung is stored together as a single lump.',
  "Ici les prêts ne sont pas classés par emprunteur ni par date. Ils sont classés par le prix auquel ils meurent. Tous les prêts posés sur le même barreau sont stockés ensemble, en un seul bloc."],
 ['Nobody has to trigger the cleanup, and nobody is paid to. Every single action anyone takes on this pool — a swap, a deposit, a repayment — runs the cleanup first, then does what was asked. So it is always up to date, because it cannot not be.',
  "Personne n'a besoin de déclencher le nettoyage, et personne n'est payé pour le faire. Chaque action que quelqu'un effectue sur cette réserve, un échange, un dépôt, un remboursement, lance d'abord le nettoyage, puis fait ce qui était demandé. C'est donc toujours à jour, parce que ça ne peut pas ne pas l'être."],
 ['The price falls hard. Because loans are filed by the price at which they die, finding the dead ones is not a search — everything at or below the current price is underwater, by definition. Five whole rungs, found instantly, with no list to go through.',
  "Le prix chute fort. Comme les prêts sont classés par le prix auquel ils meurent, trouver les morts n'est pas une recherche : tout ce qui est au niveau du prix courant ou en dessous est sous l'eau, par définition. Cinq barreaux entiers, trouvés instantanément, sans aucune liste à parcourir."],
 ['They are closed one rung at a time, and here is why that matters: closing a rung costs the same whether it holds one loan or ten thousand. This is why the system does not fall over in a crash, which is exactly when other designs get overwhelmed and grind to a halt.',
  "Ils sont fermés un barreau à la fois, et voici pourquoi c'est important : fermer un barreau coûte la même chose qu'il porte un prêt ou dix mille. C'est pour ça que le système ne s'effondre pas pendant un krach, précisément au moment où d'autres designs sont submergés et se bloquent."],
 ['One rung is too big to handle: closing it would cost more than the liquidity providers can absorb. So it is not closed. It is not written down as a loss either, and it is not quietly spread across everyone\'s balance. It is simply left pending, and retried on every transaction from now on.',
  "Un barreau est trop gros pour être traité : le fermer coûterait plus que ce que les liquidity providers peuvent absorber. Il n'est donc pas fermé. Il n'est pas non plus inscrit en perte, ni discrètement étalé sur le solde de tout le monde. Il est simplement laissé en attente, et réessayé à chaque transaction à partir de maintenant."],
 ['This is the part that separates a good design from a dangerous one. If the cleanup could ever fail outright, the entire pool would be frozen forever, because every action runs the cleanup first. So it never fails — it skips what it cannot handle. Trading, repaying and withdrawing all keep working, and that ordinary activity is what refills the pool.',
  "C'est la partie qui sépare un bon design d'un design dangereux. Si le nettoyage pouvait échouer franchement, toute la réserve serait gelée à jamais, puisque chaque action lance d'abord le nettoyage. Il n'échoue donc jamais : il saute ce qu'il ne peut pas traiter. Échanger, rembourser et retirer continuent de fonctionner, et c'est cette activité ordinaire qui remplit à nouveau la réserve."],
 ['And the stuck collateral puts itself on sale. After a crash the pool offers it at a discount that gets a little better every block, until somebody finds it worth buying. Nobody organises this auction and nobody is paid to run it. The pool either trades its way out, or it waits.',
  "Et le collateral bloqué se met lui-même en vente. Après un krach, la réserve le propose avec une décote qui s'améliore un peu à chaque bloc, jusqu'à ce que quelqu'un trouve ça intéressant. Personne n'organise cette enchère et personne n'est payé pour la tenir. La réserve s'en sort par ses propres échanges, ou elle attend."]
]

};
